grass:
  n_clinical: 5
  window_clinical: 7
  th_pollen: 3.0
  th_sum: 30.0
  day_threshold: 3.0

birch:
  n_clinical: 5
  window_clinical: 7
  th_pollen: 10.0
  th_sum: 100.0
  day_threshold: 10.0

ragweed:
  n_clinical: 5
  window_clinical: 7
  th_pollen: 3.0
  th_sum: 30.0
  day_threshold: 3.0

olive:
  n_clinical: 5
  window_clinical: 7
  th_pollen: 20.0
  th_sum: 200.0
  day_threshold: 20.0

cypress:
  n_clinical: 5
  window_clinical: 7
  th_pollen: 20.0
  th_sum: 200.0
  day_threshold: 20.0



